name: updateWordleWords
on:
  push:
    paths:
      - 'allWords.csv'

jobs:
  steps:
    - run: rm wordleWords.csv
    - run: rm repeatLetterRemovedWordleWords.csv
    - run: python3 wordListFinder 0