name: updateWordleWords
on:
  push:
    paths:
      - 'allWords.csv'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Print dir 1
      run: ls -a
    - name: Print dir 2
      run: pwd
    - name: change dir
      run: cd ..
    - name: Print dir 3
      run: ls -a
    - name: Print dir 4
      run: pwd
    - name: Remove wordle words
      run: rm wordleWords.csv
    - name: Remove repeat letter
      run: rm repeatLetterRemovedWordleWords.csv
    - name: run wordListFinder to regenerate files
      run: python3 wordListFinder.py 0
