name: updateWordleWords
on:
  push:
    paths:
      - 'allWords.csv'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Update wordle words
      run: |
        ls -a
        pwd
        cd ..
        ls -a
        pwd
        rm wordleWords.csv
        rm repeatLetterRemovedWordleWords.csv
        python3 wordListFinder.py 0
